
services:
  ## Infrastructure Services
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_MULTIPLE_DATABASES: inventory-service,order-service
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - shopverse-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGOINITDB_DATABASE: product-service
    networks:
      - shopverse-network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - shopverse-network


  broker:
    image: apache/kafka:latest
    hostname: broker
    container_name: broker
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:29093
      KAFKA_LISTENERS: PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - shopverse-network

  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - shopverse-network

  ## Application Services
  discovery-server:
    image: shopverse/discovery-server:1.0-SNAPSHOT
    container_name: discovery-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - shopverse-network

  api-gateway:
    image: shopverse/api-gateway:1.0-SNAPSHOT
    container_name: api-gateway
#    volumes:
#      - ./keys:/app/keys
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - redis
    networks:
      - shopverse-network

  product-service:
    image: shopverse/product-service:1.0-SNAPSHOT
    container_name: product-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongodb
      - discovery-server
      - api-gateway
    networks:
      - shopverse-network

  order-service:
    image: shopverse/order-service:1.0-SNAPSHOT
    container_name: order-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - broker
      - discovery-server
      - api-gateway
      - zipkin
    networks:
      - shopverse-network

  inventory-service:
    image: shopverse/inventory-service:1.0-SNAPSHOT
    container_name: inventory-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_USERNAME=admin
      - DATABASE_PASSWORD=admin
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://zipkin:9411/api/v2/spans
    depends_on:
      - postgres
      - discovery-server
      - api-gateway
    networks:
      - shopverse-network

  notification-service:
    image: shopverse/notification-service:1.0-SNAPSHOT
    container_name: notification-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - broker
      - discovery-server
      - api-gateway
    networks:
      - shopverse-network

  ## Prometheus
  prometheus:
    image: prom/prometheus:v3.7.3
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - shopverse-network
    depends_on:
      - product-service
      - inventory-service
      - order-service
      - notification-service
      - discovery-server

  grafana:
    image: grafana/grafana-oss:11.2.0
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
#    links:
#      - prometheus:prometheus
    networks:
      - shopverse-network
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password

networks:
  shopverse-network:
    driver: bridge

volumes:
  postgres-data:
  mongodb-data: