global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'microservices'
    metrics_path: '/actuator/prometheus'
    eureka_sd_configs:
      - server: http://discovery-server:8761/eureka
    relabel_configs:
      - source_labels: [ __meta_eureka_app_name ]
        target_label: application
      - source_labels: [ __meta_eureka_app_instance_id ]
        target_label: instance
#    file_sd_configs:
#      - files:
#          - /etc/prometheus/service-config.json