apiVersion: v1
kind: ConfigMap
metadata:
  name: shopverse-config
  namespace: shopverse
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://zipkin:9411/api/v2/spans"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
